apiVersion: apps/v1
kind: Deployment
metadata:
  name: udacity-capstone-project-${LABEL_VERSION}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: udacity-capstone-project
      version: ${LABEL_VERSION}
  template:
    metadata:
      labels:
        app: udacity-capstone-project
        version: ${LABEL_VERSION}
    spec:
      containers:
      - name: udacity-capstone-project
        image: ${DOCKER_IMAGE}
        ports:
        - containerPort: 80
