apiVersion: v1
kind: Service
metadata:
  name: udacity-capstone-project
spec:
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
    name: http
  selector:
    app: udacity-capstone-project
    version: ${LABEL_VERSION}
  type: LoadBalancer